name: Generate .meta.json if missing

on:
  push:
    paths:
      - '**/*.json'

jobs:
  generate-meta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run meta checker
        run: node .github/scripts/meta-checker.js

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Add missing .meta.json files" || echo "No changes"
          git push
